name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Triggers the workflow on the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t arsalwali00/python_live_chat_app .

    - name: Push the Docker image
      run: docker push arsalwali00/python_live_chat_app
